Repository resumeme/Frontend, pull requests merged in 2023-12, with the labels that each got.

#260 Gmmq 777 fix: 피드백 완료 후 처리 관련 작업
  src/components/organisms/RemoteControlPannel/RemoteControlPannel.tsx
  src/routes/FeedbackResumeLoader.tsx
  src/routes/GuestLoader.tsx
  src/routes/UserLoader.tsx
  src/routes/router.tsx
Labels: 🔨 Fix

#262 hotfix: 이력서 작성완료 버튼 추가
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
Labels: 🌟 Feat

#264 Gmmq 779 fix: 401에러 처리 수정
  src/App.tsx
  src/api/axios.ts
  src/constants/errorMessage.ts
Labels: 🔨 Fix

#263 Gmmq 778 fix: resumes query 없을 때 처리
  src/queries/resume/delete/useDeleteResume.ts
Labels: 🔨 Fix

#265 fix: 모든 페이지 이동 시 스크롤 위치 초기화
  src/pages/ResumePages/FeedbackResumePage/FeedbackResumePage.tsx
  src/pages/ResumePages/ResumeDetailPage/ResumeDetailPage.tsx
  src/routes/FocusLayout.tsx
  src/routes/Layout.tsx
  src/routes/MainLayout.tsx
Labels: 🛠 Refactor, 🔨 Fix
