Repository resumeme/Frontend, pull requests merged in 2023-11, with the labels that each got.

#24 feat: NotFoundPage 버튼 추가 및 스타일 수정
  src/pages/NotFoundPage/NotFoundPage.tsx
Labels: 🎨 Style, 🌟 Feat

#21 Gmmq 242 refactor: form input 컴포넌트 제거 및 Form 관련 컴포넌트 추가
  src/components/atoms/FormLabel/FormLabel.tsx
  src/components/atoms/FormLabel/index.stories.tsx
  src/components/molecules/FormControl/FormControl.tsx
  src/components/molecules/FormControl/index.stories.tsx
  src/components/molecules/FormControl/index.ts
  src/components/molecules/FormDateInput/FormDateInput.tsx
  src/components/molecules/FormDateInput/index.stories.tsx
  src/components/molecules/FormDateInput/index.ts
  src/components/molecules/FormInput/FormInput.tsx
  src/components/molecules/FormInput/index.stories.tsx
  src/components/molecules/FormInput/index.ts
  src/components/molecules/FormTextInput/FormTextInput.tsx
  src/components/molecules/FormTextInput/index.stories.tsx
  src/components/molecules/FormTextInput/index.ts
  src/pages/SignUpPage/CommonSignUpPage.tsx
  src/theme/components/input.ts
Labels: 🌟 Feat

#23 Gmmq 169 feat: 이력서 작성 페이지 - 업무경험 작성 UI 개발
  package-lock.json
  package.json
  src/components/molecules/CategoryAddHeader/CategoryAddHeader.tsx
  src/components/molecules/CategoryAddHeader/index.stories.tsx
  src/components/molecules/CategoryAddHeader/index.ts
  src/components/molecules/FormControl/FormControl.tsx
  src/components/molecules/FormControl/index.stories.tsx
  src/components/molecules/FormDateInput/FormDateInput.tsx
  src/components/molecules/FormDateInput/index.stories.tsx
  src/components/molecules/FormTextInput/FormTextInput.tsx
  src/components/molecules/TermInput/TermInput.tsx
  src/components/molecules/TermInput/index.stories.tsx
  src/components/molecules/TermInput/index.ts
  src/components/organisms/Grid/index.ts
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeCategoryCareer/ResumeCategoryCareer.tsx
  src/components/organisms/ResumeCategoryCareer/index.stories.tsx
  src/components/organisms/ResumeCategoryCareer/index.ts
  src/hooks/index.ts
  src/hooks/useStorage.ts
  src/types/career.ts
  src/types/dateString.ts
  src/types/position.ts
  src/utils/getOneYearLater.ts
  src/utils/index.ts
Labels: 🌟 Feat

#25 fix: 폴더 구조 변경
  src/pages/EventPage/ApplyEventPage.tsx
  src/pages/EventPages/ApplyEventPage/ApplyEventPage.tsx
  src/pages/EventPages/ApplyEventPage/index.ts
  src/pages/EventPages/CreateEventPage/CreateEventPage.tsx
  src/pages/EventPages/CreateEventPage/index.ts
  src/pages/EventPages/EventDetailPage/EventDetailPage.tsx
  src/pages/EventPages/EventDetailPage/index.ts
  src/pages/EventPages/EventListPage/EventListPage.tsx
  src/pages/EventPages/EventListPage/index.ts
  src/pages/MyPage/MentorMyPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/index.ts
  src/pages/ProfilePages/MenteeEditProfilePage/MenteeEditProfilePage.tsx
  src/pages/ProfilePages/MenteeEditProfilePage/index.ts
  src/pages/ProfilePages/MentorEditProfilePage/MentorEditProfilePage.tsx
  src/pages/ProfilePages/MentorEditProfilePage/index.ts
  src/pages/ResumePages/CommentResumePage/CommentResumePage.tsx
  src/pages/ResumePages/CommentResumePage/index.ts
  src/pages/ResumePages/CreateResumePage/CreateResumePage.tsx
  src/pages/ResumePages/CreateResumePage/index.ts
  src/pages/ResumePages/EditResumePage/EditResumePage.tsx
  src/pages/ResumePages/EditResumePage/index.ts
  src/pages/ResumePages/ResumeDetailPage/ResumeDetailPage.tsx
  src/pages/ResumePages/ResumeDetailPage/index.ts
  src/pages/SignUpPages/CommonSignUpPage/CommonSignUpPage.tsx
  src/pages/SignUpPages/CommonSignUpPage/index.ts
  src/pages/SignUpPages/MenteeSignUpPage/MenteeSignUpPage.tsx
  src/pages/SignUpPages/MenteeSignUpPage/index.ts
  src/pages/SignUpPages/MentorSignUpPage/MentorSignUpPage.tsx
  src/pages/SignUpPages/MentorSignUpPage/index.ts
  src/pages/WriteReviewPage/WriteReviewPage.tsx
  src/pages/WriteReviewPage/index.ts
  src/routes/router.tsx
Labels: 🛠 Refactor

#27 Gmmq 167 feat: 로그인/회원가입 레이아웃
  src/App.tsx
  src/routes/FocusLayout.tsx
Labels: 🎨 Style, 🌟 Feat

#26 Gmmq 248 fix: footer 오류 해결
  src/components/organisms/Footer/Footer.const.ts
  src/components/organisms/Footer/Footer.tsx
  src/components/organisms/Footer/index.ts
  src/routes/Layout.tsx
Labels: 🔨 Fix

#29 Gmmq 158 feat: 소셜 (카카오) 로그인 연동
  src/api/user/postOAuthSignIn.ts
  src/constants/environments.ts
  src/constants/index.ts
  src/pages/SignInPage/OAuthRedirectPage.tsx
  src/pages/SignUpPages/CommonSignUpPage/CommonSignUpPage.tsx
  src/queries/usePostOAuthSignIn.ts
  src/routes/router.tsx
  src/stores/useCacheKeyStore.ts
Labels: 🌟 Feat

#30 Gmmq 173 feat: create event api 연결, 연결 관련 타입 수정
  src/components/molecules/FormControl/index.stories.tsx
  src/components/molecules/FormTextInput/FormTextInput.tsx
  src/components/molecules/FormTextInput/index.stories.tsx
  src/components/molecules/LabelCheckboxGroup/LabelCheckboxGroup.tsx
  src/components/molecules/TermInput/TermInput.tsx
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/templates/CreateEventTemplate/CreateEventTemplate.tsx
  src/services/eventService.ts
Labels: 🌟 Feat

#28 Gmmq 168 feat: 이력서 작성 페이지 - 기본 프로필 입력 부분 UI 및 사소한 오류 수정
  package-lock.json
  package.json
  src/components/atoms/TitleInput/TitleInput.tsx
  src/components/atoms/TitleInput/index.stories.ts
  src/components/organisms/ResumeBasicInput/LinkIconBox.tsx
  src/components/organisms/ResumeBasicInput/ResumeBasicInput.tsx
  src/components/organisms/ResumeBasicInput/index.ts
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/routes/Layout.tsx
Labels: 🎨 Style, 🔨 Fix

#32 Gmmq 309 fix: create event page api 타입 수정
  src/api/event/postCreateEvent.ts
  src/components/molecules/FormControl/index.stories.tsx
  src/components/molecules/FormDateInput/FormDateInput.tsx
  src/components/molecules/FormTextInput/FormTextInput.tsx
  src/components/molecules/FormTextInput/index.stories.tsx
  src/components/molecules/LabelCheckboxGroup/LabelCheckboxGroup.tsx
  src/components/molecules/TermInput/TermInput.tsx
  src/components/templates/CreateEventTemplate/CreateEventTemplate.tsx
  src/queries/usePostCreateEvent.ts
  src/services/eventService.ts
  src/services/index.ts
  src/types/event.ts
Labels: 🔨 Fix

#36 Gmmq 174 feat: 이력서 업무경험 작성 api 연결
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/api/resume/create/postResumeCareer.ts
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeCategoryCareer/ResumeCategoryCareer.tsx
  src/components/organisms/ResumeCategoryCareer/index.stories.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/components/templates/EditResumeTemplate/index.ts
  src/pages/ResumePages/EditResumePage/EditResumePage.tsx
  src/queries/resume/create/usePostResumeCareer.ts
  src/types/career.ts
  src/types/errorResponse.ts
Labels: 🌟 Feat

#33 Gmmq 289 feat: 이력서 작성 - 기본 정보 입력 부분 개발
  src/api/resume/postResumeBasicInfo.ts
  src/components/atoms/TitleInput/TitleInput.tsx
  src/components/atoms/TitleInput/index.stories.ts
  src/components/molecules/FormTextInput/FormTextInput.tsx
  src/components/organisms/ResumeBasicInput/BasicInfoForm.tsx
  src/components/organisms/ResumeBasicInput/LinkIconBox.tsx
  src/components/organisms/ResumeBasicInput/ReferenceLinkForm.tsx
  src/components/organisms/ResumeBasicInput/ResumeBasicInput.tsx
  src/components/organisms/ResumeBasicInput/TitleInputForm.tsx
  src/hooks/useStringToArray.tsx
  src/queries/usePostResumeBasicInfo.ts
  src/types/userInfo.ts
Labels: 🌟 Feat

#38 Gmmq 314 hotfix: 이력서 작성 버튼, 로그인 라우팅 처리
  src/api/resume/create/postCreateResume.ts
  src/components/organisms/Header/Header.tsx
  src/config/paths.ts
  src/constants/environments.ts
  src/constants/index.ts
  src/pages/MainPage/MainPage.tsx
  src/queries/resume/create/usePostCreateResume.ts
Labels: 📢 긴급요청

#40 Gmmq 174 feat: 주요 업무 경험 제목, 날짜 필수값 처리
  src/api/resume/create/postResumeCareer.ts
  src/components/molecules/DynamicTags/DynamicTags.tsx
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/hooks/useStringToArray.tsx
  src/queries/resume/create/usePostResumeCareer.ts
Labels: 🔨 Fix

#43 Gmmq 174 fix: 주요 업무 경험 제목, 날짜 필수값 처리 + 기술스택 태그 컴포넌트 분리
  src/api/resume/create/postResumeCareer.ts
  src/components/molecules/DynamicTags/DynamicTags.tsx
  src/components/molecules/DynamicTags/index.ts
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/hooks/useStringToArray.tsx
  src/queries/resume/create/usePostResumeCareer.ts
Labels: 🔨 Fix

#37 Gmmq 264 feat: project block UI 개발
  src/components/atoms/FormLabel/FormLabel.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryProject/index.stories.tsx
  src/components/organisms/ResumeCategoryProject/index.ts
  src/types/project.ts
Labels: 🎨 Style, 🌟 Feat

#39 Gmmq 265 feat: awards block UI, react-hook-form 관련 개발
  src/components/atoms/FormLabel/FormLabel.tsx
  src/components/organisms/ResumeCategoryAwards/AwardsForm.tsx
  src/components/organisms/ResumeCategoryAwards/index.stories.tsx
  src/components/organisms/ResumeCategoryAwards/index.ts
  src/types/awards.ts
Labels: 🎨 Style, 🌟 Feat

#46 Gmmq 268 feat: 이력서 외국어 (어학성적) 입력 폼 UI, react hook form
  src/components/organisms/ResumeCategoryLanguage/LanguageForm.tsx
  src/components/organisms/ResumeCategoryLanguage/index.stories.tsx
  src/components/organisms/ResumeCategoryLanguage/index.ts
  src/types/language.ts
Labels: 🌟 Feat

#45 Gmmq 300 feat: 업무경험 상세 컴포넌트 개발
  src/api/resume/details/getResumeCareer.ts
  src/components/organisms/ResumeCategoryCareer/ResumeCategory.tsx
  src/components/organisms/ResumeCategoryCareer/index.ts
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/create/usePostResumeCareer.ts
  src/queries/resume/details/useGetResumeCareer.ts
Labels: 🌟 Feat, 🔒 작업중

#48 Gmmq 300 feat: 업무 경험 작성 후 낙관적 업데이트, ResumeCategory 작성
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/create/usePostResumeCareer.ts
Labels: 🌟 Feat

#49 Gmmq 271 feat: 이력서 교육 카테고리 작성, 상세 api 연결
  src/api/resume/create/postResumeTraining.ts
  src/api/resume/details/getResumeTraining.ts
  src/components/molecules/FormTextInput/FormTextInput.tsx
  src/components/organisms/ResumeCategoryCareer/ResumeCategory.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
  src/components/organisms/ResumeDetails/index.ts
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/create/usePostResumeTraining.ts
  src/queries/resume/details/useGetResumeTraining.ts
Labels: 🌟 Feat

#50 Gmmq 270 feat: awards block 등록 api 연결
  src/api/resume/create/postResumeAward.ts
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryAwards/index.stories.tsx
  src/components/organisms/ResumeCategoryAwards/index.ts
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/create/usePostResumeAward.ts
  src/types/award.ts
Labels: 🌟 Feat

#47 Gmmq 269 feat: project block 에 api 연결 작업
  src/api/resume/create/postResumeProject.ts
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryProject/index.stories.tsx
  src/components/organisms/ResumeCategoryTraining/index.stories.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/create/usePostRusumeProject.ts
Labels: 🌟 Feat

#52 Gmmq 299 feat: project 블럭 저장 내용 보여주기
  src/api/resume/details/getResumeProject.ts
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/organisms/ResumeDetails/index.ts
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/create/usePostRusumeProject.ts
  src/queries/resume/details/useGetResumeProject.ts
Labels: 🌟 Feat

#51 Gmmq 273 feat: 외국어 카테고리 get,post api 연결
  src/api/resume/create/postResumeLanguage.ts
  src/api/resume/details/getResumeLanguage.ts
  src/components/organisms/ResumeCategoryLanguage/LanguageForm.tsx
  src/components/organisms/ResumeDetails/LanguageDetails.tsx
  src/components/organisms/ResumeDetails/index.ts
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/create/usePostResumeLanguage.ts
  src/queries/resume/details/useGetResumeLanguage.ts
Labels: 🌟 Feat

#53 Gmmq 272 feat: 이력서 활동 post, get api 연결, 상세컴포넌트 생성
  src/api/resume/create/postResumeActivity.ts
  src/api/resume/details/getResumeActivities.ts
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeDetails/ActivityDetails.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/create/usePostResumeActivity.ts
  src/queries/resume/details/useGetResumeActivities.ts
Labels: 🌟 Feat

#55 Gmmq 335 feat: 이력서 카테고리 상세 데이터 전체 뿌려주기
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
Labels: 🌟 Feat

#54 Gmmq 298 feat: award block api view
  src/api/resume/details/getResumeAward.ts
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeDetails/AwardDetails.tsx
  src/components/organisms/ResumeDetails/index.ts
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/create/usePostResumeAward.ts
  src/queries/resume/details/useGetResumeAward.ts
Labels: 🌟 Feat

#56 chore: 이력서 활동 get api 주석 해제, index 추가
  src/components/organisms/ResumeDetails/index.ts
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
Labels: 🧹 Chore

#58 Gmmq 263 feat: 이력서 작성 페이지 - 상단 기본입력 폼 기능 구현 및 스타일 수정
  src/api/resume/create/patchResumeBasicInfo.ts
  src/api/resume/create/postResumeLink.ts
  src/api/resume/create/postResumeTitle.ts
  src/components/atoms/TitleInput/TitleInput.tsx
  src/components/molecules/ReferenceLinkBox/ReferenceLinkBox.tsx
  src/components/molecules/ReferenceLinkBox/index.ts
  src/components/organisms/ResumeBasicInput/BasicInfoForm.tsx
  src/components/organisms/ResumeBasicInput/LinkIconBox.tsx
  src/components/organisms/ResumeBasicInput/LinkItem.tsx
  src/components/organisms/ResumeBasicInput/ReferenceLinkForm.tsx
  src/components/organisms/ResumeBasicInput/ResumeBasicInput.tsx
  src/components/organisms/ResumeBasicInput/TitleInputForm.tsx
  src/components/organisms/ResumeCategoryCareer/ResumeCategory.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/create/usePatchResumeBasicInfo.ts
  src/queries/resume/create/usePostResumeLink.ts
  src/queries/resume/create/usePostResumeTitle.ts
  src/theme/components/index.ts
  src/theme/components/textarea.ts
  src/theme/index.tsx
  src/types/referenceLink.ts
  src/types/userInfo.ts
Labels: 🎨 Style, 🌟 Feat

#57 Gmmq 336 fix:project block UI input
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
Labels: 🔨 Fix

#64 Gmmq 377 fix: axios header 수정
  src/api/resume/create/patchResumeBasicInfo.ts
  src/api/resume/create/postCreateResume.ts
  src/api/resume/create/postResumeActivity.ts
  src/api/resume/create/postResumeAward.ts
  src/api/resume/create/postResumeCareer.ts
  src/api/resume/create/postResumeLanguage.ts
  src/api/resume/create/postResumeLink.ts
  src/api/resume/create/postResumeProject.ts
  src/api/resume/create/postResumeTitle.ts
  src/api/resume/create/postResumeTraining.ts
  src/api/resume/details/getResumeActivities.ts
  src/api/resume/details/getResumeAward.ts
  src/api/resume/details/getResumeCareer.ts
  src/api/resume/details/getResumeLanguage.ts
  src/api/resume/details/getResumeProject.ts
  src/api/resume/details/getResumeTraining.ts
  src/pages/SignInPage/OAuthRedirectPage.tsx
Labels: 📢 긴급요청

#60 Gmmq 317 feat: dynamic tags (기술스택 태그 배열) 삭제 기능, 간격 스타일 수정
  src/components/molecules/DynamicTags/DynamicTags.tsx
  src/components/organisms/ResumeBasicInput/BasicInfoForm.tsx
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/hooks/useStringToArray.tsx
Labels: 🌟 Feat

#63 Gmmq 279 fix: LabelCheckBox에서 ref에 관련된 오류를 수정
  src/components/molecules/LabelCheckboxGroup/LabelCheckboxGroup.tsx
Labels: 🔨 Fix

#61 Gmmq 319 feat: mentor block UI 개발
  src/components/molecules/MentorProfile/MentorProfile.tsx
  src/pages/EventPages/EventDetailPage/EventDetailPage.tsx
  src/types/event.ts
  src/types/mentor.ts
Labels: 🌟 Feat

#62 Gmmq 320 feat: mentor block api 연결 작업
  .storybook/preview.tsx
  src/api/user/getMentorDetail.ts
  src/components/molecules/MentorProfile/index.stories.tsx
  src/components/molecules/MentorProfile/index.ts
  src/pages/EventPages/EventDetailPage/EventDetailPage.tsx
  src/queries/user/details/useGetMentorDetail.tsx
  src/routes/router.tsx
Labels: 🌟 Feat

#66 Gmmq 288 feat: 이력서 제목 자동저장 기능 구현
  src/api/resume/create/patchResumeTitle.ts
  src/components/atoms/TitleInput/TitleInput.tsx
  src/components/organisms/ResumeBasicInput/TitleInputForm.tsx
  src/hooks/useDebounce.ts
  src/queries/resume/create/usePatchResumeTitle.ts
  src/queries/resume/create/usePostResumeTitle.ts
Labels: 🎨 Style, 🌟 Feat

#69 Gmmq 351 style: 이력서 상세 페이지 레이아웃 구현
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/components/templates/ResumeDetailTemplate/index.ts
  src/pages/ResumePages/ResumeDetailPage/ResumeDetailPage.tsx
Labels: 🎨 Style

#68 Gmmq 321 feat: event info UI 개발
  src/api/event/details/getEventDetail.ts
  src/components/molecules/MentorProfile/MentorProfile.tsx
  src/components/molecules/MentorProfile/index.stories.tsx
  src/components/organisms/EventDetail/EventContent.tsx
  src/components/organisms/EventDetail/EventDetail.tsx
  src/components/organisms/EventDetail/EventTime.tsx
  src/components/organisms/EventDetail/EventTitle.tsx
  src/components/organisms/EventDetail/MentorCareerContent.tsx
  src/components/organisms/EventDetail/MentorCareerTitle.tsx
  src/components/organisms/EventDetail/index.ts
  src/pages/EventPages/EventDetailPage/EventDetailPage.tsx
  src/types/event.ts
Labels: 🌟 Feat

#70 Gmmq 323 feat: 로그인 페이지 UI
  src/assets/images/kakao-logo.svg
  src/components/molecules/OAuthSignInButton/OAuthSignInButton.tsx
  src/components/molecules/OAuthSignInButton/index.stories.tsx
  src/components/molecules/OAuthSignInButton/index.ts
  src/components/templates/SignInTemplate/SignInTemplate.tsx
  src/components/templates/SignInTemplate/index.ts
  src/config/assets.ts
  src/constants/index.ts
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/SignInPage/SignInPage.tsx
Labels: 🌟 Feat

#72 Gmmq 337 fix: 사용하지 않는 타입 제거, Project 블럭 - DynamicTag 교체
  src/api/resume/create/patchResumeBasicInfo.ts
  src/api/resume/postResumeBasicInfo.ts
  src/components/organisms/ResumeBasicInput/BasicInfoForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/types/basicInfo.ts
  src/types/userInfo.ts
Labels: 🛠 Refactor, 🔨 Fix

#73 Gmmq 325 feat: 공통 회원가입 페이지 UI, 카드형 라디오버튼 컴포넌트 개발
  src/assets/images/mentee-outlined.svg
  src/assets/images/mentor-outlined.svg
  src/components/atoms/BorderBox/BorderBox.tsx
  src/components/organisms/ RadioCardGroup/RadioCard.tsx
  src/components/organisms/ RadioCardGroup/RadioCardGroup.tsx
  src/components/organisms/ RadioCardGroup/index.ts
  src/components/templates/SignUpCommonTemplate/SignUpCommonTemplate.tsx
  src/config/assets.ts
  src/constants/index.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/index.ts
  src/pages/SignUpPages/CommonSignUpPage/CommonSignUpPage.tsx
  src/pages/SignUpPages/CommonSignUpPage/index.ts
  src/pages/SignUpPages/MenteeSignUpPage/MenteeSignUpPage.tsx
  src/pages/SignUpPages/MenteeSignUpPage/index.ts
  src/pages/SignUpPages/MentorSignUpPage/MentorSignUpPage.tsx
  src/pages/SignUpPages/MentorSignUpPage/index.ts
  src/routes/router.tsx
  src/types/fields.ts
  src/types/roles.ts
  src/types/signUp.ts
Labels: 🌟 Feat

#71 Gmmq 343 style: 이력서 상세 페이지 상단부 화면 UI 구현
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
Labels: 🎨 Style

#77 Gmmq 344 style: 이력서 상세 페이지 - 업무경험 UI 구현
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
Labels: 🎨 Style

#76 Gmmq 326 feat: 가입 페이지 스텝별로 템플릿 컴포넌트 분리, 스텝 및 데이터 상태관리
  src/components/templates/SignUpCommonTemplate/SignUpCommonTemplate.tsx
  src/components/templates/SignUpCommonTemplate/index.ts
  src/components/templates/SignUpCompleteTemplate/SignUpCompleteTemplate.tsx
  src/components/templates/SignUpCompleteTemplate/index.ts
  src/components/templates/SignUpMenteeTemplate/SignUpMenteeTemplate.tsx
  src/components/templates/SignUpMenteeTemplate/index.ts
  src/components/templates/SignUpMentorTemplate/SignUpMentorTemplate.tsx
  src/components/templates/SignUpMentorTemplate/index.ts
  src/hooks/usePrompt.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/types/signUp.ts
Labels: 🌟 Feat

#78 Gmmq 327 feat: 멘티 가입 페이지
  src/components/organisms/SignUpHeader/SignUpHeader.tsx
  src/components/organisms/SignUpHeader/index.ts
  src/components/templates/SignUpCommonTemplate/SignUpCommonTemplate.tsx
  src/components/templates/SignUpMenteeTemplate/SignUpMenteeTemplate.tsx
  src/constants/index.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/theme/components/button.ts
Labels: 🌟 Feat

#74 Gmmq 322 feat: event info api 연결
  src/api/event/details/getEventDetail.ts
  src/components/molecules/MentorProfile/MentorProfile.tsx
  src/components/organisms/EventDetail/EventDetail.tsx
  src/components/organisms/EventDetail/EventTitle.tsx
  src/pages/EventPages/EventDetailPage/EventDetailPage.tsx
  src/queries/event/details/useGetEventDetail.ts
Labels: 🌟 Feat

#75 Gmmq 310 fix: errors에서 error로 변경, 의미에 맞게 사용, 일관성 개선
  src/components/atoms/TitleInput/TitleInput.tsx
  src/components/molecules/FormDateInput/FormDateInput.tsx
  src/components/molecules/FormTextarea/FormTextarea.tsx
  src/components/molecules/FormTextarea/index.stories.tsx
  src/components/molecules/TermInput/TermInput.tsx
  src/components/organisms/ResumeBasicInput/BasicInfoForm.tsx
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
  src/components/templates/CreateEventTemplate/CreateEventTemplate.tsx
Labels: 🛠 Refactor, 🔨 Fix

#79 style: 이력서 상세 페이지 - 프로젝트 카테고리 UI 구현
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/types/project.ts
Labels: 🎨 Style

#81 Gmmq 346 style: 이력서 상세 페이지 - 교육 UI 구현
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
  src/components/organisms/ResumeDetails/index.ts
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/types/training.ts
Labels: 🎨 Style, 🔨 Fix

#82 Gmmq 349 style: 이력서 상세 페이지 - 활동, 외국어 UI 구현 및 목업 데이터 분리
  src/components/organisms/ResumeDetails/ActivityDetails.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/organisms/ResumeDetails/LanguageDetails.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/templates/ResumeDetailTemplate/ResumeDetail.const.ts
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/types/activity.ts
  src/types/award.ts
Labels: 🎨 Style, 🌟 Feat

#84 Gmmq 329 feat: 멘토/멘티 회원가입 api 연결, 가입완료 페이지 UI
  src/api/user/postOAuthSignIn.ts
  src/api/user/postOAuthSignUp.ts
  src/components/molecules/LabelCheckboxGroup/LabelCheckboxGroup.tsx
  src/components/templates/SignUpCommonTemplate/SignUpCommonTemplate.tsx
  src/components/templates/SignUpCompleteTemplate/SignUpCompleteTemplate.tsx
  src/config/paths.ts
  src/constants/index.ts
  src/main.tsx
  src/pages/SignInPage/OAuthRedirectPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/queries/usePostOAuthSignIn.ts
  src/queries/usePostOAuthSignUp.ts
  src/stores/useCacheKeyStore.ts
  src/types/fields.ts
  src/types/position.ts
  src/types/signUp.ts
Labels: 🌟 Feat

#65 Gmmq 357 feat: 이력서 작성 취소 버튼 활성화, 이력서 작성 페이지 구조 refactor
  src/components/atoms/BorderBox/BorderBox.tsx
  src/components/atoms/Button/Button.tsx
  src/components/molecules/CategoryAddHeader/CategoryAddHeader.tsx
  src/components/molecules/ConfirmModal/ConfirmModal.tsx
  src/components/molecules/ConfirmModal/index.ts
  src/components/molecules/SubmitButtonGroup/SubmitButtonGroup.tsx
  src/components/molecules/SubmitButtonGroup/index.stories.tsx
  src/components/molecules/SubmitButtonGroup/index.ts
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeCategoryCareer/ResumeCategory.tsx
  src/components/organisms/ResumeCategoryLanguage/LanguageForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/hooks/useHandleFormState.ts
Labels: 🛠 Refactor, 🌟 Feat

#85 Gmmq 399 feat: FeedbackInput 구현
  package-lock.json
  package.json
  src/components/molecules/FeedbackInput/FeedbackInput.tsx
  src/components/molecules/FeedbackInput/index.stories.tsx
Labels: 🌟 Feat

#86 Gmmq 382 feat: 로그인 확인, 토큰 저장, 불러오기
  src/api/event/details/getEventDetail.ts
  src/api/resume/create/patchResumeBasicInfo.ts
  src/api/resume/create/patchResumeTitle.ts
  src/api/resume/create/postCreateResume.ts
  src/api/resume/create/postResumeActivity.ts
  src/api/resume/create/postResumeAward.ts
  src/api/resume/create/postResumeCareer.ts
  src/api/resume/create/postResumeLanguage.ts
  src/api/resume/create/postResumeLink.ts
  src/api/resume/create/postResumeProject.ts
  src/api/resume/create/postResumeTitle.ts
  src/api/resume/create/postResumeTraining.ts
  src/api/resume/details/getResumeActivities.ts
  src/api/resume/details/getResumeAward.ts
  src/api/resume/details/getResumeCareer.ts
  src/api/resume/details/getResumeLanguage.ts
  src/api/resume/details/getResumeProject.ts
  src/api/resume/details/getResumeTraining.ts
  src/api/user/getMentorDetail.ts
  src/components/molecules/LabelCheckboxGroup/LabelCheckboxGroup.tsx
  src/pages/SignInPage/OAuthRedirectPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/types/user.ts
  src/utils/cookie.ts
Labels: 🌟 Feat

#87 Gmmq 384 feat: 유저 정보 저장하기
  src/api/axios.ts
  src/hooks/useUser.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/SignInPage/OAuthRedirectPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
Labels: 🌟 Feat

#88 Gmmq 415 feat: 첨삭 총평 리모컨 컴포넌트
  src/components/atoms/RemoteControl/RemoteControl.tsx
  src/components/atoms/RemoteControl/index.stories.tsx
  src/components/atoms/RemoteControl/index.ts
  src/components/organisms/RemoteControlComment/RemoteControlComment.tsx
  src/components/organisms/RemoteControlComment/index.stories.tsx
  src/components/organisms/RemoteControlComment/index.ts
Labels: 🌟 Feat

#89 Gmmq 416 refactor: 이력서 카테고리 상세 Details 컴포넌트 리팩토링
  src/components/molecules/CategoryAddHeader/CategoryAddHeader.tsx
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeCategoryCareer/ResumeCategoryCareer.tsx
  src/components/organisms/ResumeCategoryCareer/index.stories.tsx
  src/components/organisms/ResumeCategoryDetails/ResumeCategoryDetails.tsx
  src/components/organisms/ResumeCategoryDetails/index.ts
  src/components/organisms/ResumeCategoryLanguage/LanguageForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
  src/components/organisms/ResumeDetails/ActivityDetails.tsx
  src/components/organisms/ResumeDetails/AwardDetails.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/organisms/ResumeDetails/LanguageDetails.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/components/templates/ResumeDetailTemplate/ResumeDetail.const.ts
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/types/career.ts
Labels: 🛠 Refactor

#90 Gmmq 468 hotfix: 멘토, 멘티 가입 페이지 나중에 작성하기
  src/components/templates/SignUpMentorTemplate/SignUpMentorTemplate.tsx
  src/pages/SignUpPage/SignUpPage.tsx
Labels: 🔨 Fix

#91 Gmmq 469 fix: 이력서 저장 후 Form 닫히도록 수정, 취소/저장 버튼 위치 교체
  src/components/molecules/SubmitButtonGroup/SubmitButtonGroup.tsx
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeCategoryLanguage/LanguageForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
Labels: 🔨 Fix

#93 Gmmp 471 style: 교육 폼 왼쪽 정렬
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
Labels: 🎨 Style

#94 Gmmq 470 fix: 이력서 교육 카테고리 get 안되는 문제 수정
  src/queries/resume/create/usePostResumeTraining.ts
  src/queries/resume/details/useGetResumeTraining.ts
Labels: 🔨 Fix

#92 Gmmq 437 feat: 마이페이지 프로필 컴포넌트 개발
  src/components/organisms/Profile/ImageCard.tsx
  src/components/organisms/Profile/Profile.tsx
  src/components/organisms/Profile/UserDetail.tsx
  src/components/organisms/Profile/index.ts
  src/pages/MyPage/MyPage.tsx
  src/types/user.ts
Labels: 🎨 Style, 🌟 Feat

#97 Gmmq 485 hotfix: suspense fallback 추가
  src/components/atoms/Spinner/Spinner.tsx
  src/components/atoms/Spinner/index.stories.ts
  src/components/atoms/Spinner/index.ts
  src/pages/SignInPage/OAuthRedirectPage.tsx
  src/routes/Layout.tsx
Labels: 🔨 Fix, 📢 긴급요청

#95 Gmmq 467 fix: 관심 도메인 주석 해제
  src/components/molecules/LabelCheckboxGroup/LabelCheckboxGroup.tsx
Labels: 🧹 Chore, 🔨 Fix

#96 Gmmq 391 feat: 유효하지 않은 토큰 처리
  src/api/axios.ts
  src/hooks/useUser.ts
Labels: 🌟 Feat

#98 Gmmq 439 feat: 마이페이지 멘토 - 이벤트 정보 UI 개발
  src/components/organisms/EventDetail/EventTime.tsx
  src/components/organisms/Profile/EventItem.tsx
  src/components/organisms/Profile/EventProfile.tsx
  src/components/organisms/Profile/Profile.tsx
  src/pages/MyPage/MyPage.tsx
  src/types/event.ts
  src/utils/formatDate.ts
Labels: 🎨 Style, 🌟 Feat

#99 Gmmq 456 fix: border box 패딩 값 수정, 마진 값 수정
  src/components/templates/CreateEventTemplate/CreateEventTemplate.tsx
Labels: 🔨 Fix

#100 Gmmq 455 feat: url 관련 검사, placeholder 통일 작업
  src/components/organisms/ResumeBasicInput/ReferenceLinkForm.tsx
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/constants/index.ts
Labels: 🔨 Fix

#101 Gmmq 457 fix: 이벤트 생성 성공 시 페이지 이동
  src/api/event/postCreateEvent.ts
  src/components/templates/CreateEventTemplate/CreateEventTemplate.tsx
  src/queries/usePostCreateEvent.ts
Labels: 🔨 Fix

#104 Gmmq 492 hotfix: resumes 엔드포인트 수정
  src/api/resume/create/postResumeActivity.ts
  src/api/resume/create/postResumeAward.ts
  src/api/resume/create/postResumeCareer.ts
  src/api/resume/create/postResumeLanguage.ts
  src/api/resume/create/postResumeLink.ts
  src/api/resume/create/postResumeProject.ts
  src/api/resume/create/postResumeTitle.ts
  src/api/resume/create/postResumeTraining.ts
  src/api/resume/details/getResumeActivities.ts
  src/api/resume/details/getResumeAward.ts
  src/api/resume/details/getResumeCareer.ts
  src/api/resume/details/getResumeLanguage.ts
  src/api/resume/details/getResumeProject.ts
  src/api/resume/details/getResumeTraining.ts
  src/api/resume/postResumeBasicInfo.ts
Labels: 🔨 Fix, 📢 긴급요청

#102 Gmmq 458 fix: 자기소개, 인원 현황 스타일 수정
  src/components/molecules/MentorProfile/MentorProfile.tsx
Labels: 🎨 Style, 🔨 Fix

#106 Gmmq 500 refactor: 이력서 카테고리 useQuery 키 상수 처리
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeCategoryLanguage/LanguageForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
  src/queries/resume/categoryKeys.const.ts
  src/queries/resume/create/usePostResumeActivity.ts
  src/queries/resume/create/usePostResumeAward.ts
  src/queries/resume/create/usePostResumeCareer.ts
  src/queries/resume/create/usePostResumeLanguage.ts
  src/queries/resume/create/usePostResumeTraining.ts
  src/queries/resume/create/usePostRusumeProject.ts
  src/queries/resume/details/useGetResumeActivities.ts
  src/queries/resume/details/useGetResumeAward.ts
  src/queries/resume/details/useGetResumeCareer.ts
  src/queries/resume/details/useGetResumeLanguage.ts
  src/queries/resume/details/useGetResumeProject.ts
  src/queries/resume/details/useGetResumeTraining.ts
Labels: 🛠 Refactor, 📢 긴급요청

#103 Gmmq 449 feat: 이력서 수정, 삭제 버튼 UI
  src/components/molecules/OptionsButton/EditDeleteOptionsButton.tsx
  src/components/molecules/OptionsButton/OptionsButton.tsx
  src/components/molecules/OptionsButton/index.stories.tsx
  src/components/molecules/OptionsButton/index.ts
  src/components/organisms/ResumeCategoryDetails/ResumeCategoryDetails.tsx
  src/components/organisms/ResumeDetails/ActivityDetails.tsx
  src/components/organisms/ResumeDetails/AwardDetails.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/organisms/ResumeDetails/LanguageDetails.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
Labels: 🌟 Feat

#107 Gmmq 440 feat: 마이페이지 멘토 - 각 이벤트 별 이력서 컴포넌트 개발
  src/components/organisms/Profile/EventItem.tsx
  src/components/organisms/Profile/EventProfile.tsx
  src/components/organisms/Profile/ResumeList.tsx
Labels: 🎨 Style, 🌟 Feat

#111 Gmmq 390 feat: auth - 로그아웃 기능 구현
  src/api/user/postSignOut.ts
  src/components/organisms/Header/Header.tsx
  src/hooks/useUser.ts
  src/queries/usePostSignOut.ts
Labels: 🌟 Feat

#105 Gmmq 400 feat: 이력서 첨삭 페이지 - 첨삭 코멘트 뷰어 UI
  src/components/molecules/FeedbackInput/index.ts
  src/components/molecules/FeedbackView/FeedbackView.tsx
  src/components/molecules/FeedbackView/index.stories.tsx
  src/components/molecules/FeedbackView/index.ts
  src/utils/formatDate.ts
Labels: 🎨 Style, 🌟 Feat

#108 Gmmq 445 feat: 이력서 관리 페이지 - 이력서 리스트 UI 개발
  src/components/organisms/ResumeManagementItem/ResumeItem.tsx
  src/components/organisms/ResumeManagementItem/index.ts
  src/components/templates/ResumeManagementTemplate/ResumeManagementTemplate.tsx
  src/components/templates/ResumeManagementTemplate/index.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/ResumePages/ResumeManagementPage/ResumeManagementPage.tsx
  src/pages/ResumePages/ResumeManagementPage/index.ts
  src/routes/router.tsx
  src/types/event.ts
Labels: 🎨 Style, 🌟 Feat

#109 Gmmq 446 feat: 이력서 관리 페이지 - 이력서에 대한 이벤트 참여 현황 UI 개발
  src/components/molecules/ManagementPanel/ManagementPanel.tsx
  src/components/molecules/ManagementPanel/index.ts
  src/components/organisms/Profile/EventItem.tsx
  src/components/organisms/ResumeManagementItem/ResumeItem.tsx
Labels: 🎨 Style, 🌟 Feat

#110 Gmmq 450 feat: 이력서 수정 기능 + api 연결
  src/api/resume/edit/patchResumeActivity.ts
  src/api/resume/edit/patchResumeAward.ts
  src/api/resume/edit/patchResumeCareer.ts
  src/api/resume/edit/patchResumeLanguage.ts
  src/api/resume/edit/patchResumeProject.ts
  src/api/resume/edit/patchResumeTraining.ts
  src/components/molecules/OptionsButton/OptionsButton.tsx
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeCategoryDetails/ResumeCategoryDetails.tsx
  src/components/organisms/ResumeCategoryLanguage/LanguageForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
  src/components/organisms/ResumeDetails/ActivityDetails.tsx
  src/components/organisms/ResumeDetails/AwardDetails.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/organisms/ResumeDetails/LanguageDetails.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/useOptimisticUpdateCategory.ts
  src/types/activity.ts
  src/types/api/patchResumeCategory.ts
  src/types/award.ts
  src/types/career.ts
  src/types/language.ts
  src/types/project.ts
  src/types/props/detailsComponentProps.ts
  src/types/props/formComponentProps.ts
  src/types/resume/categories.ts
  src/types/training.ts
Labels: 🌟 Feat

#114 hotfix: api response 변경사항 반영
  src/api/resume/details/getResumeActivities.ts
  src/api/resume/details/getResumeAward.ts
  src/api/resume/details/getResumeCareer.ts
  src/api/resume/details/getResumeLanguage.ts
  src/api/resume/details/getResumeProject.ts
  src/api/resume/details/getResumeTraining.ts
  src/queries/resume/details/useGetResumeActivities.ts
  src/queries/resume/details/useGetResumeAward.ts
  src/queries/resume/details/useGetResumeCareer.ts
  src/queries/resume/details/useGetResumeLanguage.ts
  src/queries/resume/details/useGetResumeProject.ts
  src/queries/resume/details/useGetResumeTraining.ts
Labels: 🔨 Fix, 📢 긴급요청

#113 Gmmq 507 feat: 마이페이지 관련 개발
  src/api/resume/delete/deleteResume.ts
  src/components/organisms/Profile/Profile.tsx
  src/components/organisms/ResumeManagementItem/ResumeItem.tsx
  src/components/templates/ResumeManagementTemplate/ResumeManagementTemplate.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/ResumePages/ResumeManagementPage/ResumeManagementPage.tsx
  src/pages/ResumePages/ResumeManagementPage/index.ts
  src/queries/resume/delete/useDeleteResume.ts
  src/routes/router.tsx
Labels: 🛠 Refactor, 🌟 Feat

#117 Gmmq 451 feat: 이력서 삭제 기능 + api 연동
  src/api/resume/delete/deleteResumeCategoryBlock.ts
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeCategoryLanguage/LanguageForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
  src/components/organisms/ResumeDetails/ActivityDetails.tsx
  src/components/organisms/ResumeDetails/AwardDetails.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/organisms/ResumeDetails/LanguageDetails.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/queries/resume/useOptimisticDeleteCategory.ts
  src/queries/resume/useOptimisticPatchCategory.ts
  src/types/api/deleteResumeCategory.ts
Labels: 🌟 Feat

#115 Gmmq 352 feat: 이력서 상세 페이지 API 수정, 이력서 작성/수정 페이지 API 관련 부분 수정
  src/api/resume/details/getResumeBasic.ts
  src/api/resume/details/getResumeDetails.ts
  src/api/resume/details/getResumeReferenceLinks.ts
  src/components/molecules/ReferenceLinkBox/ReferenceLinkBox.tsx
  src/components/organisms/ResumeBasicInput/LinkItem.tsx
  src/components/organisms/ResumeBasicInput/ReferenceLinkForm.tsx
  src/components/organisms/ResumeBasicInput/ResumeBasicInput.tsx
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/queries/resume/categoryKeys.const.ts
  src/queries/resume/details/index.ts
  src/queries/resume/details/useGetResumeBasic.ts
  src/queries/resume/details/useGetResumeDetails.ts
  src/queries/resume/details/useGetResumeReferenceLinks.ts
  src/types/referenceLink.ts
Labels: 🌟 Feat

#125 Gmmq 547 fix: basicInfo GET API 함수에서 phoneNumber 포매팅 추가
  src/api/resume/details/getResumeBasic.ts
  src/utils/formatPhoneNumber.ts
Labels: 🔨 Fix, 🌟 Feat

#120 Gmmq 545 fix: 희망 직무, 보유 기술이 없을 때 UI 렌더링 하지 않기
  src/api/resume/create/postResumeLink.ts
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
Labels: 🔨 Fix

#118 Gmmq 549 fix: 기술 스택 관련 개선
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/hooks/useStringToArray.tsx
Labels: 🔨 Fix

#129 Revert "hotfix: basicInfo GET API 함수에서 phoneNumber 포매팅 추가 (#125)"
  src/api/resume/details/getResumeBasic.ts
  src/utils/formatPhoneNumber.ts
Labels: 🧹 Chore

#130 Gmmq 547 feat: basicInfo GET API 함수에서 phoneNumber 포매팅 추가
  src/api/resume/details/getResumeBasic.ts
  src/hooks/useUser.ts
  src/utils/formatPhoneNumber.ts
Labels: 🌟 Feat

#123 Gmmq 552 fix: api project type 변경 반영
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/types/project.ts
Labels: 🔨 Fix

#127 Gmmq 550 fix: 취득 일자 validate 변경 작업
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
Labels: 🔨 Fix

#128 fix: 회원가입 -> 로그인 페이지 리다이렉션 조건 추가
  src/pages/SignUpPage/SignUpPage.tsx
Labels: 🔨 Fix

#119 Gmmq 557 fix: 이벤트 시작 날짜 - 검사 기능 수정
  src/components/molecules/FormDateInput/FormDateInput.tsx
  src/components/molecules/TermInput/TermInput.tsx
  src/components/molecules/TermInput/index.stories.tsx
  src/components/templates/CreateEventTemplate/CreateEventTemplate.tsx
Labels: 🔨 Fix

#122 Gmmq 558 fix: 마이 페이지 관련 개선 작업
  src/components/organisms/Profile/EventItem.tsx
  src/components/organisms/Profile/ImageCard.tsx
  src/components/organisms/Profile/UserDetail.tsx
  src/components/templates/ResumeManagementTemplate/ResumeManagementTemplate.tsx
Labels: 🔨 Fix

#126 Gmmq 556 fix: 로그아웃 성공하면 홈 화면으로 이동
  src/queries/usePostSignOut.ts
Labels: 🔨 Fix

#116 Gmmq 443 feat: 이벤트 관련 이력서 불러오기 api 연결
  src/api/event/details/getManagementEvents.ts
  src/pages/MyPage/MyPage.tsx
  src/queries/event/details/useGetManagementEvents.ts
  src/types/user.ts
Labels: 🌟 Feat, 🔒 작업중

#121 Gmmq 464 feat: 이벤트 신청 페이지 UI + 이력서 리스트 불러오기 연동
  src/api/resume/getMyResumes.ts
  src/components/atoms/Spinner/Spinner.tsx
  src/components/molecules/MentorProfile/MentorProfile.tsx
  src/components/molecules/MentorProfile/index.stories.tsx
  src/components/molecules/Modal/Modal.tsx
  src/components/molecules/ResumeListItem/ResumeListItem.tsx
  src/components/molecules/ResumeListItem/index.stories.tsx
  src/components/molecules/ResumeListItem/index.ts
  src/components/organisms/RadioCardGroup/RadioCard.tsx
  src/components/organisms/RadioCardGroup/RadioCardGroup.tsx
  src/components/organisms/ResumeSelect/ResumeSelect.tsx
  src/components/organisms/ResumeSelect/index.stories.tsx
  src/components/organisms/ResumeSelect/index.ts
  src/components/templates/SignUpCommonTemplate/index.stories.tsx
  src/config/paths.ts
  src/pages/EventPages/ApplyEventPage/ApplyEventPage.tsx
  src/pages/EventPages/ApplyEventPage/index.ts
  src/pages/EventPages/EventDetailPage/EventDetailPage.tsx
  src/queries/resume/useGetMyResumes.ts
  src/routes/router.tsx
  src/types/resume/resumeListItem.ts
Labels: 🌟 Feat

#124 Gmmq 554 fix: 이력서 빈 배열일 경우 예외처리
  src/components/organisms/ResumeSelect/ResumeSelect.tsx
Labels: 🔨 Fix

#131 Gmmq 513 feat: 공통 정보 수정 UI 개발
  src/components/atoms/Button/Button.tsx
  src/components/molecules/SubmitButtonGroup/SubmitButtonGroup.tsx
  src/components/templates/EditProfileTemplate/CommonInput.tsx
  src/components/templates/EditProfileTemplate/EditMenteeProfileTemplate.tsx
  src/components/templates/EditProfileTemplate/EditMentorProfileTemplate.tsx
  src/components/templates/EditProfileTemplate/index.ts
  src/pages/ProfilePages/EditProfilePage/EditProfilePage.tsx
  src/pages/ProfilePages/EditProfilePage/index.ts
  src/pages/ProfilePages/MenteeEditProfilePage/MenteeEditProfilePage.tsx
  src/pages/ProfilePages/MenteeEditProfilePage/index.ts
  src/routes/router.tsx
Labels: 🎨 Style, 🌟 Feat

#132 Gmmq 518 feat: 멘토, 멘티 정보 수정 UI
  src/components/molecules/Modal/CareerContentModal.tsx
  src/components/molecules/Modal/index.ts
  src/components/templates/EditProfileTemplate/EditMenteeProfileTemplate.tsx
  src/components/templates/EditProfileTemplate/EditMentorProfileTemplate.tsx
  src/components/templates/SignUpMentorTemplate/SignUpMentorTemplate.tsx
  src/types/mentee.ts
  src/types/mentor.ts
Labels: 🎨 Style, 🌟 Feat

#133 Gmmq 515 feat: 멘토 정보 수정하기 api
  src/api/event/details/getManagementEvents.ts
  src/api/user/edit/patchMentorProfile.ts
  src/components/organisms/Profile/ImageCard.tsx
  src/components/organisms/Profile/UserDetail.tsx
  src/components/templates/EditProfileTemplate/EditMentorProfileTemplate.tsx
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/hooks/useUser.ts
  src/queries/user/edit/userPatchMentorProfile.tsx
  src/utils/formatPhoneNumber.ts
Labels: 🎨 Style, 🌟 Feat

#134 Gmmq 517 feat: 멘티 정보 수정 api 작업
  src/api/user/edit/patchMenteeProfile.ts
  src/components/templates/EditProfileTemplate/EditMenteeProfileTemplate.tsx
  src/components/templates/EditProfileTemplate/EditMentorProfileTemplate.tsx
  src/queries/user/edit/userPatchMenteeProfile.tsx
Labels: 🌟 Feat

#135 Gmmq 466 feat: 이벤트 신청 api 연결
  src/api/event/postEventApply.ts
  src/components/organisms/ResumeSelect/ResumeSelect.tsx
  src/constants/errorMessage.ts
  src/constants/index.ts
  src/queries/event/usePostEventApply.ts
  src/types/errorResponse.ts
Labels: 🌟 Feat

#138 Gmmq 522 feat: 이벤트 그리드 작성
  src/components/molecules/Card/index.ts
  src/components/molecules/EventGridItem/EventGridItem.tsx
  src/components/molecules/EventGridItem/index.stories.tsx
  src/components/organisms/EventGrid/EventGrid.tsx
  src/components/organisms/EventGrid/dummy.ts
  src/components/organisms/EventGrid/index.stories.tsx
  src/components/organisms/EventGrid/index.ts
  src/components/templates/EventGridTemplate/EventGridTemplate.tsx
  src/components/templates/GridTemplate/index.ts
  src/pages/EventPages/EventListPage/EventListPage.tsx
Labels: 🌟 Feat

#137 Gmmq 523 feat: 이벤트 그리드 아이템 UI
  src/components/atoms/Label/Label.tsx
  src/components/atoms/Label/index.stories.ts
  src/components/molecules/Card/index.ts
  src/components/molecules/EventGridItem/EventGridItem.tsx
  src/components/molecules/EventGridItem/index.stories.tsx
  src/components/molecules/EventGridItem/index.ts
  src/components/organisms/EventGrid/EventGrid.tsx
  src/components/organisms/EventGrid/dummy.ts
  src/components/organisms/EventGrid/index.stories.tsx
  src/components/organisms/EventGrid/index.ts
  src/components/organisms/Profile/UserDetail.tsx
  src/components/templates/EventGridTemplate/EventGridTemplate.tsx
  src/components/templates/GridTemplate/index.ts
  src/constants/index.ts
  src/constants/position.ts
  src/pages/EventPages/EventListPage/EventListPage.tsx
  src/types/position.ts
Labels: 🛠 Refactor, 🌟 Feat

#136 Gmmq 512 fix:header UI 변경
  src/components/molecules/OptionsButton/OptionsButton.tsx
  src/components/organisms/Header/Header.tsx
  src/config/paths.ts
  src/pages/ResumePages/ManagementResumePage/ManagementResumePage.tsx
  src/pages/ResumePages/ManagementResumePage/index.ts
  src/routes/router.tsx
  src/theme/components/avatar.ts
Labels: 🎨 Style, 🌟 Feat

#142 hotfix: phoneNumber가 있을 경우에만 포매팅한 전화번호 렌더링하기
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
Labels: 🔨 Fix, 📢 긴급요청

#139 Gmmq 569 feat: 내 이력서 관리 페이지 - 내 이력서 탭 UI 개발
  src/components/organisms/ResumeManagementItem/ResumeItem.tsx
  src/components/templates/ResumeManagementTemplate/ResumeManagementTemplate.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/ResumePages/ManagementResumePage/ManagementResumePage.tsx
  src/types/event.ts
  src/types/resume/resumeListItem.ts
Labels: 🎨 Style

#140 Gmmq 570 feat: 첨삭 신청 내역 UI 개발
  src/components/organisms/FeedbackManagementItem/FeedbackManagementItem.tsx
  src/components/organisms/FeedbackManagementItem/index.ts
  src/components/organisms/ResumeManagementItem/ResumeItem.tsx
  src/components/templates/FeedbackManagementTemplate/FeedbackManagementTemplate.tsx
  src/components/templates/FeedbackManagementTemplate/index.ts
  src/config/paths.ts
  src/constants/index.ts
  src/constants/status.ts
  src/pages/ResumePages/ManagementResumePage/ManagementResumePage.tsx
  src/types/resume/resumeListItem.ts
  src/types/resume/status.ts
Labels: 🎨 Style, 🌟 Feat

#147 Gmmq 574 fix: 이벤트 상세 페이지 api 타입 수정
  src/api/event/details/getManagementEvents.ts
  src/components/molecules/MentorProfile/MentorProfile.tsx
  src/components/molecules/MentorProfile/index.stories.tsx
  src/components/organisms/EventDetail/EventDetail.tsx
  src/components/organisms/EventDetail/EventTitle.tsx
  src/components/organisms/Profile/EventProfile.tsx
  src/pages/EventPages/EventDetailPage/EventDetailPage.tsx
  src/types/event.ts
Labels: 🔨 Fix, 📢 긴급요청

#148 Gmmq 575 fix: 배포환경에서 로그인 실패 시 재요청 문제 해결
  src/api/axios.ts
Labels: 🔨 Fix, 📢 긴급요청

#143 Gmmq 571 feat: resume management navigator UI 개발
  src/components/atoms/Button/Button.tsx
  src/components/organisms/ResumeNavigator/ResumeNavigator.tsx
  src/components/organisms/ResumeNavigator/index.ts
  src/components/templates/FeedbackManagementTemplate/FeedbackManagementTemplate.tsx
  src/components/templates/ResumeManagementTemplate/ResumeManagementTemplate.tsx
  src/pages/ResumePages/ManagementResumePage/ManagementResumePage.tsx
Labels: 🎨 Style, 🌟 Feat

#144 Gmmq 529 feat: 이력서 작성 페이지 - 기본정보 입력 및 수정 기능 완성
  src/api/resume/create/patchResumeBasicInfo.ts
  src/api/resume/details/getResumeBasic.ts
  src/api/resume/postResumeBasicInfo.ts
  src/components/organisms/ResumeBasicInput/BasicInfoForm.tsx
  src/components/organisms/ResumeBasicInput/BasicInfoView.stories.tsx
  src/components/organisms/ResumeBasicInput/BasicInfoView.tsx
  src/components/organisms/ResumeBasicInput/ResumeBasicInput.tsx
  src/components/organisms/ResumeBasicInput/TitleInputForm.tsx
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/queries/resume/create/usePatchResumeBasicInfo.ts
  src/queries/resume/details/useGetResumeBasic.ts
  src/queries/usePostResumeBasicInfo.ts
  src/types/basicInfo.ts
Labels: 🎨 Style, 🌟 Feat

#145 Gmmq 448 feat: 이력서 관리 페이지 api 연결 작업
  src/api/resume/details/getResumeReferenceLinks.ts
  src/api/resume/getFeedbackResumes.ts
  src/api/resume/getMyResumes.ts
  src/pages/ResumePages/ManagementResumePage/ManagementResumePage.tsx
  src/queries/resume/useGetFeedbackResumes.ts
  src/queries/resume/useGetMyResumes.ts
Labels: 🌟 Feat

#141 Gmmq 521 feat: 이벤트 전체 조회 api
  src/api/event/details/getEventDetail.ts
  src/api/event/details/getManagementEvents.ts
  src/api/event/getEventList.ts
  src/api/event/postCreateEvent.ts
  src/components/molecules/EventGridItem/EventGridItem.tsx
  src/components/molecules/EventGridItem/index.stories.tsx
  src/components/molecules/FormControl/index.stories.tsx
  src/components/molecules/FormTextInput/index.stories.tsx
  src/components/molecules/MentorProfile/MentorProfile.tsx
  src/components/molecules/MentorProfile/index.stories.tsx
  src/components/organisms/EventDetail/EventDetail.tsx
  src/components/organisms/EventGrid/EventGrid.tsx
  src/components/organisms/EventGrid/dummy.ts
  src/components/organisms/EventGrid/index.stories.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Profile/EventItem.tsx
  src/components/organisms/Profile/EventProfile.tsx
  src/components/organisms/Profile/ResumeList.tsx
  src/components/templates/CreateEventTemplate/CreateEventTemplate.tsx
  src/components/templates/EventGridTemplate/EventGridTemplate.tsx
  src/components/templates/SignUpCompleteTemplate/SignUpCompleteTemplate.tsx
  src/config/paths.ts
  src/constants/eventStatus.ts
  src/constants/index.ts
  src/pages/SignInPage/OAuthRedirectPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/queries/event/useGetEventList.ts
  src/queries/usePostSignOut.ts
  src/types/event/event.ts
  src/types/event/eventList.ts
  src/types/eventStatus.ts
  src/types/pageData.ts
Labels: 🌟 Feat

#151 fix: 이력서 블럭 id 필드명 수정 반영
  src/api/resume/create/postResumeCareer.ts
  src/components/organisms/ResumeCategoryDetails/ResumeCategoryDetails.tsx
  src/components/organisms/ResumeDetails/ActivityDetails.tsx
  src/components/organisms/ResumeDetails/AwardDetails.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/organisms/ResumeDetails/LanguageDetails.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
  src/types/activity.ts
  src/types/award.ts
  src/types/career.ts
  src/types/language.ts
  src/types/project.ts
  src/types/training.ts
Labels: 🔨 Fix, 📢 긴급요청

#152 fix: 이벤트 상태 상수 반영
  src/components/molecules/EventGridItem/EventGridItem.tsx
  src/components/organisms/EventDetail/EventTitle.tsx
Labels: 🔨 Fix, 📢 긴급요청

#153 fix: 멘토 경력연차 80 미만 validation 추가
  src/components/templates/SignUpMentorTemplate/SignUpMentorTemplate.tsx
Labels: 🔨 Fix, 📢 긴급요청

#155 refactor: 이력서 작성 useOptimisticPostMutation 통합
  src/api/resume/create/postResumeActivity.ts
  src/api/resume/create/postResumeAward.ts
  src/api/resume/create/postResumeCareer.ts
  src/api/resume/create/postResumeLanguage.ts
  src/api/resume/create/postResumeProject.ts
  src/api/resume/create/postResumeTraining.ts
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeCategoryLanguage/LanguageForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
  src/queries/resume/useOptimsticPostCategory.ts
  src/types/api/postResumeCategory.ts
Labels: 🛠 Refactor, 📢 긴급요청

#156 fix: 이벤트 신청 성공 후 모달 닫히도록 수정
  src/components/organisms/ResumeSelect/ResumeSelect.tsx
Labels: 🌟 Feat, 📢 긴급요청

#150 Gmmq 585 fix: 멘토일 때 이력서 관리 버튼 안보이게 수정
  src/components/organisms/Header/Header.tsx
  src/config/paths.ts
Labels: 🔨 Fix

#154 Gmmq 589 fix: 이벤트 상세 페이지 신청하기 버튼 비활성화, 타입 변경
  src/components/molecules/EventGridItem/index.stories.tsx
  src/components/molecules/MentorProfile/MentorProfile.tsx
  src/components/molecules/MentorProfile/index.stories.tsx
  src/components/organisms/EventGrid/index.stories.tsx
  src/pages/EventPages/EventDetailPage/EventDetailPage.tsx
  src/queries/user/details/useGetMentorDetail.tsx
  src/types/event/event.ts
Labels: 🔨 Fix, 📢 긴급요청

#157 Gmmq 592 fix: 마이페이지 이벤트 없을 때 처리
  src/pages/MyPage/MyPage.tsx
  src/queries/event/details/useGetManagementEvents.ts
Labels: 🔨 Fix, 📢 긴급요청

#159 Gmmq 598 refactor: ConfirmModal EditDeleteOptionsButton으로 이동
  src/components/molecules/OptionsButton/EditDeleteOptionsButton.tsx
  src/components/organisms/ResumeDetails/ActivityDetails.tsx
  src/components/organisms/ResumeDetails/AwardDetails.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/organisms/ResumeDetails/LanguageDetails.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
  src/components/organisms/ResumeManagementItem/ResumeItem.tsx
Labels: 🛠 Refactor

#160 Gmmq 588 fix: resume detail project- 팀 선택 시 팀원 필수 입력, axios 무한 요청 해결
  src/api/axios.ts
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/constants/errorMessage.ts
Labels: 🔨 Fix, 📢 긴급요청

#162 hotfix: duties 빈배열로 보내기
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
Labels: 🔨 Fix, 📢 긴급요청

#165 Gmmq 472 feat: 이력서 첨삭 페이지
  src/components/atoms/RemoteControl/RemoteControl.tsx
  src/components/molecules/FeedbackInput/FeedbackInput.tsx
  src/components/organisms/RemoteControlPannel/RemoteControlPannel.tsx
  src/components/organisms/ResumeCategoryDetails/ResumeCategoryDetails.tsx
  src/components/templates/FeedbackResumeTemplate/FeedbackBlock.tsx
  src/components/templates/FeedbackResumeTemplate/FeedbackResumeTemplate.tsx
  src/components/templates/FeedbackResumeTemplate/index.ts
  src/pages/ResumePages/CommentResumePage/CommentResumePage.tsx
  src/pages/ResumePages/CommentResumePage/index.ts
  src/pages/ResumePages/FeedbackResumePage/FeedbackResumePage.tsx
  src/pages/ResumePages/FeedbackResumePage/index.ts
  src/routes/FeedbackLayout.tsx
  src/routes/router.tsx
Labels: 🎨 Style, 🌟 Feat

#161 Gmmq 568 feat: 페이지네이션 컴포넌트, 이벤트 그리드 페이지에 적용
  src/api/event/getEventList.ts
  src/components/molecules/Pagination/Pagination.tsx
  src/components/molecules/Pagination/index.stories.tsx
  src/components/molecules/Pagination/index.ts
  src/components/templates/EventGridTemplate/EventGridTemplate.tsx
  src/queries/event/eventKeys.const.ts
  src/queries/event/useGetEventList.ts
  src/types/pageData.ts
  src/types/pagination.ts
Labels: 🌟 Feat

#170 Gmmq 616 feat: 이력서 첨삭 페이지 데이터 렌더링
  src/api/resume/create/postResumeCareer.ts
  src/api/resume/details/getResumeCareer.ts
  src/api/resume/details/getSnapshotResume.ts
  src/api/resume/edit/patchResumeCareer.ts
  src/api/resume/feedback/getResumeFeedbacks.ts
  src/components/molecules/FeedbackView/FeedbackView.tsx
  src/components/organisms/FeedbackResumeDetails/FeedbackResumeDetails.tsx
  src/components/organisms/FeedbackResumeDetails/index.ts
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/templates/FeedbackCompleteTemplate/FeedbackCompleteTemplate.tsx
  src/components/templates/FeedbackCompleteTemplate/index.ts
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/pages/ResumePages/FeedbackCompletePage/FeedbackCompletePage.tsx
  src/queries/resume/create/usePostResumeCareer.ts
  src/queries/resume/details/useGetSnapshotResume.ts
  src/types/career.ts
  src/types/event/feedback.ts
  src/types/referenceLink.ts
  src/types/resume/allBlocks.ts
  src/types/resume/categories.ts
  src/types/resume/feedback.ts
  src/utils/formatDate.ts
Labels: 🌟 Feat

#163 Gmmq 610 feat: 첨삭 데이터 불러오기 api 연결
  src/api/resume/create/postResumeCareer.ts
  src/api/resume/details/getResumeCareer.ts
  src/api/resume/details/getSnapshotResume.ts
  src/api/resume/edit/patchResumeCareer.ts
  src/api/resume/feedback/getResumeFeedbacks.ts
  src/components/molecules/FeedbackView/FeedbackView.tsx
  src/components/organisms/FeedbackManagementItem/FeedbackManagementItem.tsx
  src/components/organisms/FeedbackResumeDetails/FeedbackResumeDetails.tsx
  src/components/organisms/FeedbackResumeDetails/index.ts
  src/components/organisms/ResumeCategoryCareer/CareerForm.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/templates/FeedbackCompleteTemplate/FeedbackCompleteTemplate.tsx
  src/components/templates/FeedbackCompleteTemplate/index.ts
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/config/paths.ts
  src/pages/ResumePages/FeedbackCompletePage/FeedbackCompletePage.tsx
  src/pages/ResumePages/FeedbackCompletePage/index.ts
  src/queries/resume/create/usePostResumeCareer.ts
  src/queries/resume/details/useGetSnapshotResume.ts
  src/queries/resume/feedback/feedbackKeys.const.ts
  src/queries/resume/feedback/useGetResumeFeedbacks.ts
  src/routes/router.tsx
  src/types/career.ts
  src/types/event/feedback.ts
  src/types/referenceLink.ts
  src/types/resume/allBlocks.ts
  src/types/resume/categories.ts
  src/types/resume/resumeListItem.ts
  src/utils/formatDate.ts
Labels: 🌟 Feat

#167 Gmmq 618 feat: 이력서 첨삭 페이지 - API 함수 및 쿼리, 첨삭 코멘트 POST 연동
  src/api/resume/feedback/patchFeedbackReject.ts
  src/api/resume/feedback/postFeedbackComment.ts
  src/components/molecules/FeedbackInput/FeedbackInput.tsx
  src/components/organisms/ResumeCategoryDetails/ResumeCategoryDetails.tsx
  src/components/templates/FeedbackResumeTemplate/FeedbackBlock.tsx
  src/components/templates/FeedbackResumeTemplate/FeedbackResumeTemplate.tsx
  src/queries/event/usePatchFeedbackReject.ts
  src/queries/event/usePostFeedbackComment.ts
  src/routes/router.tsx
  src/types/resume/feedbackComment/feedbackComment.ts
Labels: 🌟 Feat

#169 Gmmq 635 fix: 이력서 카테고리 읽기 전용 타입으로 수정 및 교체
  src/api/resume/delete/deleteResumeCategoryBlock.ts
  src/api/resume/details/getResumeActivities.ts
  src/api/resume/details/getResumeAward.ts
  src/api/resume/details/getResumeCareer.ts
  src/api/resume/details/getResumeLanguage.ts
  src/api/resume/details/getResumeProject.ts
  src/api/resume/details/getResumeTraining.ts
  src/components/organisms/FeedbackResumeDetails/FeedbackResumeDetails.tsx
  src/components/organisms/ResumeCategoryDetails/ResumeCategoryDetails.tsx
  src/components/organisms/ResumeDetails/ActivityDetails.tsx
  src/components/organisms/ResumeDetails/AwardDetails.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/organisms/ResumeDetails/LanguageDetails.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
  src/types/activity.ts
  src/types/api/deleteResumeCategory.ts
  src/types/api/patchResumeCategory.ts
  src/types/award.ts
  src/types/career.ts
  src/types/language.ts
  src/types/project.ts
  src/types/props/formComponentProps.ts
  src/types/resume/allBlocks.ts
  src/types/resume/categories.ts
  src/types/training.ts
Labels: 🔨 Fix

#164 Gmmq 606 feat: main page top UI 개발
  src/assets/images/banner-illustration.svg
  src/components/organisms/ResumeCategoryDetails/ResumeCategoryDetails.tsx
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/config/assets.ts
  src/config/paths.ts
  src/pages/MainPage/MainPage.tsx
  src/routes/Layout.tsx
  src/routes/layoutSize.const.ts
Labels: 🎨 Style, 🌟 Feat

#166 Gmmq 612 feat: main page event info UI 개발
  src/components/molecules/EventGridItem/EventGridItem.tsx
  src/components/organisms/EventGrid/EventGrid.tsx
  src/pages/MainPage/MainPage.tsx
Labels: 🛠 Refactor, 🎨 Style

#149 docs: Update README.md
  README.md
Labels: 📝 Docs

#171 Gmmq 617 feat: 이력서 첨삭 페이지 - 리모트 컨트롤 패널 api 연결
  src/api/resume/feedback/patchFeedbackComplete.ts
  src/api/resume/feedback/patchFeedbackReject.ts
  src/components/organisms/RemoteControlPannel/RejectionModalContent.tsx
  src/components/organisms/RemoteControlPannel/RemoteControlPannel.tsx
  src/components/organisms/RemoteControlPannel/RemoteControlReject.tsx
  src/queries/event/usePatchFeedbackComplete.ts
  src/types/resume/eventReject.ts
  src/types/resume/feedbackComplete.ts
Labels: 🌟 Feat

#172 Gmmq 636 refactor: router layout 변경
  src/App.tsx
  src/main.tsx
  src/routes/MainLayout.tsx
  src/routes/router.tsx
Labels: 🛠 Refactor

#178 Gmmq 586 fix: 마이 페이지 도메인 레이블 글자 변경
  src/components/molecules/LabelCheckboxGroup/LabelCheckboxGroup.tsx
  src/components/molecules/LabelCheckboxGroup/index.stories.tsx
  src/components/organisms/Profile/UserDetail.tsx
  src/constants/field.ts
  src/constants/index.ts
  src/types/fields.ts
  src/types/user.ts
Labels: 🔨 Fix

#174 Gmmq 632 fix: 멘토 마이페이지 링크 연결
  src/components/organisms/Profile/EventItem.tsx
  src/components/organisms/Profile/EventProfile.tsx
  src/config/paths.ts
  src/types/event/event.ts
Labels: 🔨 Fix, 🌟 Feat

#176 Gmmq 624 fix: 이벤트 상세 페이지 멘토 자기소개
  src/components/molecules/MentorProfile/MentorProfile.tsx
Labels: 🔨 Fix

#180 Gmmq 613 feat: 이력서 첨삭 페이지 - 전체 기능 완성 (完)
  src/api/resume/feedback/deleteFeedbackComment.ts
  src/api/resume/feedback/patchFeedbackComment.ts
  src/components/molecules/ConfirmModal/ConfirmModal.tsx
  src/components/molecules/FeedbackView/FeedbackView.tsx
  src/components/organisms/FeedbackCategoryDetails/FeedbackCategoryDetails.tsx
  src/components/organisms/FeedbackCategoryDetails/index.ts
  src/components/organisms/FeedbackResumeDetails/index.ts
  src/components/organisms/ResumeCategoryDetails/ResumeCategoryDetails.tsx
  src/components/templates/FeedbackCompleteTemplate/FeedbackCompleteTemplate.tsx
  src/components/templates/FeedbackResumeTemplate/FeedbackBlock.tsx
  src/components/templates/FeedbackResumeTemplate/FeedbackResumeTemplate.tsx
  src/queries/event/useDeleteFeedbackComment.ts
  src/queries/event/usePatchFeedbackComment.ts
  src/queries/event/usePostFeedbackComment.ts
Labels: 🌟 Feat

#177 Gmmq 619 feat: 총평 데이터 렌더링
  src/components/templates/FeedbackCompleteTemplate/FeedbackCompleteTemplate.tsx
Labels: 🌟 Feat

#179 Gmmq 641 fix: 로그인 관련 페이지 레이아웃 적용
  src/components/organisms/Header/Header.tsx
  src/config/paths.ts
  src/pages/SignInPage/OAuthRedirectPage.tsx
  src/routes/router.tsx
Labels: 🛠 Refactor, 🔨 Fix

#181 Gmmq 642 hotfix: 멘티 가입 완료 페이지 이름 띄우기
  src/components/templates/SignUpCompleteTemplate/SignUpCompleteTemplate.tsx
  src/pages/SignUpPage/SignUpPage.tsx
Labels: 🔨 Fix, 📢 긴급요청

#182 fix: 이력서 삭제 이력서 관리 페이지 낙관적 업데이트
  src/queries/resume/delete/useDeleteResume.ts
Labels: 🔨 Fix, 📢 긴급요청

#175 Gmmq 639 fix: 이벤트 상세 페이지 링크 연결, 메모 - 이력서 제목으로 변경
  src/components/organisms/FeedbackManagementItem/FeedbackManagementItem.tsx
  src/types/resume/resumeListItem.ts
Labels: 🔨 Fix, 🌟 Feat, 🔒 작업중

#185 Gmmq 656 feat: 에러 처리, 상황에 맞는 경로 이동
  src/App.tsx
  src/api/axios.ts
  src/components/atoms/Badge/Badge.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Profile/UserDetail.tsx
  src/pages/EventPages/EventDetailPage/EventDetailPage.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/queries/event/details/useGetManagementEvents.ts
  src/queries/usePostCreateEvent.ts
  src/routes/ErrorBoundary.tsx
  src/routes/router.tsx
  src/types/errorResponse.ts
  src/types/user.ts
Labels: 🔨 Fix, 🌟 Feat

#183 Gmmq 644 style: 피드백 뷰어 UI 스타일 변경 및 에러 수정
  src/components/molecules/FeedbackView/FeedbackView.tsx
  src/components/organisms/FeedbackCategoryDetails/FeedbackCategoryDetails.tsx
  src/components/templates/FeedbackResumeTemplate/FeedbackBlock.tsx
Labels: 🎨 Style, 🔨 Fix

#186 Gmmq 672 fix: 이력서 수정 페이지 관련 수정
  src/api/resume/create/postResumeLanguage.ts
  src/api/resume/details/getResumeLanguage.ts
  src/api/resume/edit/patchResumeLanguage.ts
  src/components/organisms/ResumeBasicInput/ReferenceLinkForm.tsx
  src/components/organisms/ResumeBasicInput/TitleInputForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
  src/components/templates/FeedbackResumeTemplate/FeedbackResumeTemplate.tsx
  src/components/templates/ResumeDetailTemplate/ResumeDetailTemplate.tsx
  src/hooks/useStringToArray.tsx
  src/queries/resume/useOptimisticDeleteCategory.ts
Labels: 🔨 Fix

#189 Gmmq 686 fix: v2 api 적용, 라우팅 변경 사항 적용
  src/api/resume/create/patchResumeBasicInfo.ts
  src/api/resume/create/patchResumeTitle.ts
  src/api/resume/feedback/patchFeedbackComplete.ts
  src/api/resume/feedback/patchFeedbackReject.ts
  src/components/organisms/RemoteControlPannel/RejectionModalContent.tsx
  src/components/organisms/RemoteControlPannel/RemoteControlPannel.tsx
  src/components/organisms/ResumeBasicInput/BasicInfoForm.tsx
  src/components/organisms/ResumeBasicInput/ResumeBasicInput.tsx
  src/components/organisms/ResumeBasicInput/TitleInputForm.tsx
  src/components/organisms/ResumeDetails/ActivityDetails.tsx
  src/components/organisms/ResumeDetails/AwardDetails.tsx
  src/components/organisms/ResumeDetails/CareerDetails.tsx
  src/components/organisms/ResumeDetails/LanguageDetails.tsx
  src/components/organisms/ResumeDetails/ProjectDetails.tsx
  src/components/organisms/ResumeDetails/TrainingDetails.tsx
  src/types/resume/eventReject.ts
  src/types/resume/feedbackComplete.ts
Labels: 🔨 Fix
