Repository resumeme/Frontend, pull requests merged in 2024-02, with the labels that each got.

#274 docs: README 소개 보충, 주요기능 보충, 스크린샷 추가, 기술스택 수정
  README.md
Labels: 📝 Docs

#275 fix: 로그인 화면 가운데 정렬로 수정
  src/components/templates/SignInTemplate/SignInTemplate.tsx
Labels: 🎨 Style, 🔨 Fix

#277 refactor: Form 컴포넌트 구조 리팩토링
  src/components/molecules/SubmitButtonGroup/SubmitButtonGroup.tsx
  src/components/organisms/FeedbackCateogryReflectDetails/FeedbackCategoryReflectDetails.tsx
  src/components/organisms/ResumeCategory/ResumeCategory.tsx
  src/components/organisms/ResumeCategory/index.ts
  src/components/organisms/ResumeCategoryActivity/ActivityForm.tsx
  src/components/organisms/ResumeCategoryAwards/AwardForm.tsx
  src/components/organisms/ResumeCategoryDetails/ResumeCategoryDetails.tsx
  src/components/organisms/ResumeCategoryLanguage/LanguageForm.tsx
  src/components/organisms/ResumeCategoryProject/ProjectForm.tsx
  src/components/organisms/ResumeCategoryTraining/TrainingForm.tsx
  src/components/organisms/ResumeForms/ActivityForm/ActivityForm.tsx
  src/components/organisms/ResumeForms/ActivityForm/index.stories.tsx
  src/components/organisms/ResumeForms/ActivityForm/index.ts
  src/components/organisms/ResumeForms/AwardForm/AwardForm.tsx
  src/components/organisms/ResumeForms/AwardForm/index.stories.tsx
  src/components/organisms/ResumeForms/AwardForm/index.ts
  src/components/organisms/ResumeForms/CareerForm/CareerForm.tsx
  src/components/organisms/ResumeForms/CareerForm/index.stories.tsx
  src/components/organisms/ResumeForms/CareerForm/index.ts
  src/components/organisms/ResumeForms/LanguageForm/LanguageForm.tsx
  src/components/organisms/ResumeForms/LanguageForm/index.stories.tsx
  src/components/organisms/ResumeForms/LanguageForm/index.ts
  src/components/organisms/ResumeForms/ProjectForm/ProjectForm.tsx
  src/components/organisms/ResumeForms/ProjectForm/index.stories.tsx
  src/components/organisms/ResumeForms/ProjectForm/index.ts
  src/components/organisms/ResumeForms/TrainingForm/TrainingForm.tsx
  src/components/organisms/ResumeForms/TrainingForm/index.stories.tsx
  src/components/organisms/ResumeForms/TrainingForm/index.ts
  src/components/organisms/ResumeForms/index.ts
  src/components/templates/EditResumeTemplate/EditResumeTemplate.tsx
  src/components/templates/EditResumeTemplate/index.stories.tsx
  src/components/templates/FeedbackReflectTemplate/FeedbackReflectTemplate.tsx
  src/hooks/useHandleFormState.ts
  src/types/dateString.ts
  src/types/props/formComponentProps.ts
Labels: 🛠 Refactor
